### ISSUE TITLE
Error: spawn festival ENOENT

### ISSUE THREAD

**Issue by colorwin** [afc163/fanyi#14]
My OS is Ubuntu 16.04. 

When I use "fanyi", it throw me a error:

```
events.js:163
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at exports._errnoException (util.js:1029:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:425:7)
```

**Comment by colorwin** [comment]
After I try, I find it is [say](https://github.com/Marak/say.js) command issue.

As it's notes, I install "festival"
```
sudo apt-get install festival festvox-kallpc16k
```

It is Ok.
