### ISSUE TITLE
spawn festival ENOENT

### ISSUE THREAD

**Issue by TonyRenHK** [afc163/fanyi#15]
I meet following error:

Error: spawn festival ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:442:9)
    at process._tickCallback (node.js:356:17)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)
    at node.js:968:3

do you know what happen?

**Comment by johnsonwjx** [comment]
Error: spawn festival ENOENT
    at exports._errnoException (util.js:1050:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
    at onErrorNT (internal/child_process.js:367:16)
    at _combinedTickCallback (internal/process/next_tick.js:80:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3


➜  ~ node -v
v7.10.0

**Comment by colorwin** [comment]
@johnsonwjx  Because it use "say.js" to speech, just [install it](https://github.com/Marak/say.js/).

**Comment by HuangHongRui** [comment]
Thank you ~
This command_
```sudo apt-get install festival festvox-kallpc16k```

**Comment by weite122** [comment]
Thank you，@colorwin, it works.
 Run this command.
`sudo apt-get install festival festvox-kallpc16k`

**Comment by Jsmond2016** [comment]
I try `sudo apt-get install festival festvox-kallpc16k` but not work, bash tells me this:

```
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 festival : Depends: libestools2.1 but it is not going to be installed
            Depends: alsa-utils but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

I can't install festival successfully, what should I do?

ps: my work environment is wsl:ubuntu on windows.
