### ISSUE TITLE
Input command "fanyi met" appear errors

### ISSUE THREAD

**Issue by everlose** [afc163/fanyi#20]
**everlose@everlosedeMacBook-Pro:~$ fanyi met**

```
met  英[ met ]  美[ mɛt ]  ~  iciba.com

 - v. 相遇( meet的过去式和过去分词 )；相识；开会；接触（某物）；

 1. Mut - HPI was less easily digested by trypsin and CPB than Met - HPI.
    Mut-HPI与改造前的Met-HPI 相比,不易被胰酶和羧肽酶B( CPB)降解.
 2. The Relationship of HGF , c - Met and MMP - 2 with the Pathogenesis of Endometriosis.
    c-Met及MMP -2 与子宫内膜异位症发病机理的关系.
 3. K'vod ha - met : in Hebrew, respect for the dead.
    k'vodha -met: 在希伯来语中, 它的意思是:尊重死者.
 4. MET listed products are sold in more than 7000 retail stores throughout the United States.
    通过MET认证的产品在整个美国在超过7000个零售的商店销售.
 5. MET is approved by all of those States and local jurisdictions that have an approval program.
    MET实验室 被所有那些对产品认证有审批程序的州和地方管理部门所认可.

 met  [ met ]  ~  fanyi.youdao.com

 - v. 遇见（meet的过去式和过去分词）
 - n. (Met)人名；(瑞典)梅特

 1. Met
    蛋氨酸,甲硫氨酸,代谢当量
 2. The Met
    大都会博物馆,纽约大都会艺术博物馆,大都会艺术博物馆
 3. Met Weight
    净重,毛重

 met  ~  dictionaryapi.com

  - past and past participle of
  - meet
events.js:161
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'forEach' of undefined
    at /usr/local/lib/node_modules/fanyi/lib/print.js:112:15
    at Array.forEach (native)
    at Object.exports.dictionaryapi (/usr/local/lib/node_modules/fanyi/lib/print.js:104:8)
    at /usr/local/lib/node_modules/fanyi/index.js:43:15
    at Parser.<anonymous> (/usr/local/lib/node_modules/fanyi/node_modules/xml2js/lib/xml2js.js:489:18)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:189:7)
    at SAXParser.onclosetag (/usr/local/lib/node_modules/fanyi/node_modules/xml2js/lib/xml2js.js:447:26)
    at emit (/usr/local/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/usr/local/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:629:5)
```

**Comment by afc163** [comment]
```
🎯   ~  fanyi met

 met  [ met ]  ~  fanyi.youdao.com
 
 - v. 遇见（meet的过去式和过去分词）
 - n. (Met)人名；(瑞典)梅特
 
 1. Met
    蛋氨酸,甲硫氨酸,代谢当量
 2. The Met
    大都会博物馆,纽约大都会艺术博物馆,大都会艺术博物馆
 3. Met Weight
    净重,毛重
 
 met  英[ met ]  美[ mɛt ]  ~  iciba.com
 
 - v. 相遇( meet的过去式和过去分词 )；相识；开会；接触（某物）；
 
 1. Mut - HPI was less easily digested by trypsin and CPB than Met - HPI.
    Mut-HPI与改造前的Met-HPI 相比,不易被胰酶和羧肽酶B( CPB)降解.
 2. The Relationship of HGF , c - Met and MMP - 2 with the Pathogenesis of Endometriosis.
    c-Met及MMP -2 与子宫内膜异位症发病机理的关系.
 3. K'vod ha - met : in Hebrew, respect for the dead.
    k'vodha -met: 在希伯来语中, 它的意思是:尊重死者.
 4. MET listed products are sold in more than 7000 retail stores throughout the United States.
    通过MET认证的产品在整个美国在超过7000个零售的商店销售.
 5. MET is approved by all of those States and local jurisdictions that have an approval program.
    MET实验室 被所有那些对产品认证有审批程序的州和地方管理部门所认可.
 
 met  ~  dictionaryapi.com
 
  - past and past participle of
  - meet
  - meteorological; meteorology
  - metropolitan
 ```

It works.

**Comment by everlose** [comment]
my version is "fanyi@1.1.1", how about you?

**Comment by afc163** [comment]
1.1.2

**Comment by afc163** [comment]
I think https://github.com/afc163/fanyi/pull/18 resolved this.

**Comment by everlose** [comment]
update it to 1.1.2 now, and I find it works
