### ISSUE TITLE
Program crashed with dumped stack trace

### ISSUE THREAD

**Issue by Higuoxing** [afc163/fanyi#26]
Program crashed, when I search the translation of `calling convention`
It seems that something wrong with the parser ... Maybe I could help : )

翻译 `calling convention` 这个词的时候崩溃了，我猜是解析的地方出了问题，如果您比较忙我可以帮忙看一下
PS. 很好用的小工具，我很喜欢 :)

```sh
$ fanyi calling convention

 calling convention  ~  fanyi.youdao.com

 - 调用惯例

 1. Calling convention
    调用约定,调用约定,呼叫惯例
 2. function calling convention
    函数调用约定
 3. C calling convention C
    调用约定,呼叫惯例,调用商定

  --------

 calling convention  英[ ˈkɔ:lɪŋ kənˈvenʃən ]  美[ ˈkɔlɪŋ kənˈvɛnʃən ]  ~  iciba.com


 1. Stack pointer corruption can be caused by a calling convention mismatch.
    堆叠指标损毁可能由于呼叫惯例不符合造成.
 2. Unknown unmanaged calling convention for function signature.
    函数签名的未知非托管调用约定.
 3. States that a function type encodes the default calling convention.
    表示函数类型按缺省的调用协定进行编码.
 4. Error: Type constructor has invalid calling convention.
    错误: 类型构造函数具有无效的调用约定.
 5. Then we have the struct definition, which, by default, uses the C calling convention.
    然后我们生成该结构的定义, 默认情况下, 该结构定义使用C调用约定.

  --------

events.js:167
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'entry_list' of undefined
    at /Users/me/.mutable_node_modules/lib/node_modules/fanyi/index.js:48:36
    at Parser.<anonymous> (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:307:18)
    at Parser.emit (events.js:182:13)
    at SAXParser.onerror (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:122:26)
    at emit (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:624:35)
    at error (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:1006:11)
    at Parser.exports.Parser.Parser.parseString (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:322:31)
Emitted 'error' event at:
    at Parser.exports.Parser.Parser.parseString (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:326:16)
    at Parser.parseString (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:5:59)
    at exports.parseString (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:354:19)
    at Request._callback (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/index.js:47:7)
    at Request.self.callback (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/request/request.js:185:22)
    at Request.emit (events.js:182:13)
    at Request.<anonymous> (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/request/request.js:1161:10)
    at Request.emit (events.js:182:13)
    at IncomingMessage.<anonymous> (/Users/me/.mutable_node_modules/lib/node_modules/fanyi/node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:273:13)
```

**Comment by borankux** [comment]
是不是nodejs 最新版不兼容？

**Comment by afc163** [comment]
1.2.2 released
