### ISSUE TITLE
Linux下翻译英文单词不报错，但是翻译汉语单词也能出结果，但是最后会多出报错

### ISSUE THREAD

**Issue by codevvvv9** [afc163/fanyi#28]
系统：`deepin Linux 15.7`
以前翻译汉语短语没问题，现在查出正确结果后报错如下：
```
events.js:183
      throw er; // Unhandled 'error' event
      ^

TypeError: Cannot read property 'entry_list' of undefined
    at /home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/index.js:48:36
    at Parser.<anonymous> (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:307:18)
    at emitOne (events.js:116:13)
    at Parser.emit (events.js:211:7)
    at SAXParser.onerror (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/xml2js/lib/parser.js:122:26)
    at emit (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:624:35)
    at error (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:653:5)
    at strictFail (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:677:7)
    at beginWhiteSpace (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:951:7)
    at SAXParser.write (/home/shaolin-wu/.nvm/versions/node/v8.11.4/lib/node_modules/fanyi/node_modules/sax/lib/sax.js:1006:11)
```

**Comment by afc163** [comment]
升级到最新版本再试试。
