### ISSUE TITLE
linux error

### ISSUE THREAD

**Issue by zoukang1993** [afc163/fanyi#32]
events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:229:19)
    at onErrorNT (internal/child_process.js:406:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:745:11)
    at startup (internal/bootstrap/node.js:236:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
    at onErrorNT (internal/child_process.js:406:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:560:3)

```
node  v10.6.0
npm v6.5.0

```

**Comment by afc163** [comment]
https://github.com/afc163/fanyi#error-spawn-festival-enoent
