### ISSUE TITLE
error - Unhandled 'error' event

### ISSUE THREAD

**Issue by youyiqin** [afc163/fanyi#38]
```
 aaron@YY  ~/APP  fanyi word 

⠋ events.js:173
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:248:19)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
    at onErrorNT (internal/child_process.js:431:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:17)

```

**Comment by qvjp** [comment]
https://github.com/afc163/fanyi#error-spawn-festival-enoent
