### ISSUE TITLE
fanyi anything with errors.

### ISSUE THREAD

**Issue by hotoo** [afc163/fanyi#5]
```
$ fanyi hello 

/usr/local/lib/node_modules/fanyi/node_modules/xml2json/node_modules/node-expat/node_modules/bindings/bindings.js:83
        throw e
              ^
Error: Module version mismatch. Expected 43, got 14.
    at Error (native)
    at Module.load (module.js:335:32)
    at Function.Module._load (module.js:290:12)
    at Module.require (module.js:345:17)
    at require (module.js:364:17)
    at bindings (/usr/local/lib/node_modules/fanyi/node_modules/xml2json/node_modules/node-expat/node_modules/bindings/bindings.js:76:44)
    at Object.<anonymous> (/usr/local/lib/node_modules/fanyi/node_modules/xml2json/node_modules/node-expat/lib/node-expat.js:4:32)
    at Module._compile (module.js:410:26)
    at Object.Module._extensions..js (module.js:428:10)
    at Module.load (module.js:335:32)
$ fanyi
fanyi ~ 0.2.4
Translate tools in command line
  $ fanyi word
  $ fanyi world peace
  $ fanyi chinglish
```

0.2.5 现在安装中，npm 和 tnpm 都很慢，不等了，先提 Issue。
另外 tag 和 release note 少了很多，看了 commit 不想跟这个问题有关。

**Comment by afc163** [comment]
node 版本是？

**Comment by afc163** [comment]
另外安装不慢啊。

**Comment by hotoo** [comment]
iojs@1.7.1

**Comment by afc163** [comment]
iojs@1.8.1 没有问题，你再重装下？

**Comment by hotoo** [comment]
跟使用 n 切换 node 环境有关。

**Comment by afc163** [comment]
升级了 fanyi ，不依赖 xml2json 这个需要编译的库了，现在可以随意切换 node 版本。@hotoo
