### ISSUE TITLE
Error: spawn festival ENOENT

### ISSUE THREAD

**Issue by starsareintherose** [afc163/fanyi#60]
```
guoyi@Helix:~$ fanyi 中文

⠋ events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:470:16)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn festival',
  path: 'festival',
  spawnargs: [ '--pipe' ]
}
```

**Comment by Lr-2002** [comment]
同样的错误，请问你解决了吗

**Comment by Lr-2002** [comment]
https://github.com/afc163/fanyi#error-spawn-festival-enoent
sry 这里有
