### ISSUE TITLE
undefined method `escape' for URI:Module

### ISSUE THREAD

**Issue by forliuyifei** [afc163/fanyi#61]
```
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]
$ sudo gem install fy
Fetching fy-1.0.1.gem
Fetching rainbow-3.0.0.gem
Successfully installed rainbow-3.0.0
Successfully installed fy-1.0.1
Parsing documentation for rainbow-3.0.0
Installing ri documentation for rainbow-3.0.0
Parsing documentation for fy-1.0.1
Installing ri documentation for fy-1.0.1
Done installing documentation for rainbow, fy after 0 seconds
2 gems installed
$ fy hello
/usr/local/lib/ruby/gems/3.0.0/gems/fy-1.0.1/lib/fy/fanyi.rb:17:in `query_for_hash': undefined method `escape' for URI:Module (NoMethodError)
        from /usr/local/lib/ruby/gems/3.0.0/gems/fy-1.0.1/lib/fy/fanyi.rb:13:in `initialize'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fy-1.0.1/bin/fy:29:in `new'
        from /usr/local/lib/ruby/gems/3.0.0/gems/fy-1.0.1/bin/fy:29:in `<top (required)>'
        from /usr/local/bin/fy:23:in `load'
        from /usr/local/bin/fy:23:in `<main>'
```

**Comment by forliuyifei** [comment]
不好意思，是不是走错了？

**Comment by forliuyifei** [comment]
```
$ sudo npm install fanyi -g

npm WARN npm npm does not support Node.js v10.21.0
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
/usr/local/bin/fanyi -> /usr/local/lib/node_modules/fanyi/bin/fanyi
/usr/local/bin/fy -> /usr/local/lib/node_modules/fanyi/bin/fanyi
+ fanyi@5.0.1
added 163 packages from 154 contributors in 36.853s
 ~/GIT  fy hello

⠋ events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:240:19)
    at onErrorNT (internal/child_process.js:415:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:834:11)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
    at onErrorNT (internal/child_process.js:415:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:623:3)
```

**Comment by forliuyifei** [comment]
```
$ npm -v
5.8.0
$ nodejs -v
v10.21.0
```

**Comment by forliuyifei** [comment]
```
fy hello

⠋ events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: spawn festival ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:269:19)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
    at onErrorNT (internal/child_process.js:465:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn festival',
  path: 'festival',
  spawnargs: [ '--pipe' ]
}
```

**Comment by afc163** [comment]
https://github.com/afc163/fanyi#error-spawn-festival-enoent
